# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 926cd981fc89d53673bc1d618b40259521fb7f9ab938c6de6be08c4f1ef642a7cd6b7244d2ee7b63c7483c7af16eaed7d889432c03c8747fa7c432fdf4ec3bcc

test:
  secret_key_base: 61fb5ccf2077621e7a011c679a83b6a46e8158312e553fcbd04c9a7041a401e4bfc5c6ceaa7b4f13f8ff8afc20b83e9e04fb0594b0b92eb8bf79c8a8acb582c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
